name: 'ðŸŒž CI'

on:
  workflow_dispatch:  
  pull_request:
    paths-ignore:
      - '**.md'
      - dist/**
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - dist/**
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          cache: 'yarn'

      - run: yarn install

      - run: yarn all

      - name: Compare the expected and actual dist/ directories
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            echo "::set-output name=diff::true"
          fi

      - name: commit build
        if: ${{ steps.diff.outputs.diff }}
        run: |
          git config --local user.email "maxisam@gmail.com"
          git config --local user.name "maxisam"
          git add dist/
          git commit -m "chore: build, dist updated"
          git push origin ${{ github.ref_name }}
  check:
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          jobResults: |
             ${{ needs.build.result }}
          authToken: ${{secrets.GITHUB_TOKEN}}
          checkName: CI PASSED
          sha: ${{ github.event.pull_request.head.sha || github.sha }}

  job-failure1:
    runs-on: ubuntu-latest
    steps:
    - name: step 1
      run: |
        echo "step1 failed"
        exit 1
    - name: step 2
      if: ${{ failure() }}
      run: |
        echo "step2 success"
        exit 0

  job-failure2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: step 1
      run: |
        echo "step1 failed"
        exit 1
  job-failure3:
    uses: maxisam/create-summary-check-status/.github/workflows/.workflow-a.yml@main
    with:
      isSuccess: false

  job-test:
    uses: maxisam/create-summary-check-status/.github/workflows/.workflow-a.yml@main
    needs: job-failure3
    if: needs.job-failure3.result == 'success'
    with:
      isSuccess: true

  check-failure:
    runs-on: ubuntu-latest
    needs: [job-failure1, job-failure2, job-failure3]
    if: always()
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          jobResults: |
             ${{ needs.job-failure1.result }}
             ${{ needs.job-failure2.result }}
             ${{ needs.job-failure3.result }}
          authToken: ${{secrets.GITHUB_TOKEN}}
          checkName: CI PASSED
          sha: ${{ github.event.pull_request.head.sha || github.sha }}